cd bigrepo/sage
export GMP_CONFIGURE="--enable-fat"
export SAGE_FAT_BINARY="yes"
export CFLAGS="-O2 -mmacosx-version-min=10.9 -mno-avx -mno-avx2 -mno-bmi2"
export LDFLAGS="-Wl,-platform_version,macos,10.9,11.3"
export MACOSX_DEPLOYMENT_TARGET="10.9"
export MAKE="make -j4"
CONFIG_OPTIONS="--without-system-python \
--enable-isl \
--enable-4ti2 \
--enable-benzene \
--enable-gap_packages \
--enable-latte_int \
--enable-biopython \
--enable-bliss \
--enable-buckygen \
--enable-cbc \
--enable-coxeter3 \
--enable-cryptominisat \
--enable-csdp \
--enable-e_antic \
--enable-frobby \
--enable-glucose \
--enable-gp2c \
--enable-igraph \
--enable-ipympl \
--enable-kenzo \
--enable-libnauty \
--enable-libsemigroups \
--enable-lrslib \
--enable-meataxe \
--enable-mcqd \
--enable-mpfrcx \
--enable-normaliz \
--enable-p_group_cohomology \
--enable-pari_elldata \
--enable-pari_galpol \
--enable-pari_nftables \
--enable-plantri \
--enable-primecount \
--enable-saclib \
--enable-sage_numerical_backends_coin \
--enable-pynormaliz \
--enable-pycosat \
--enable-pysingular \
--enable-sirocco \
--enable-symengine \
--enable-symengine_py \
--enable-tdlib \
--enable-tides \
--enable-topcom"
./configure $CONFIG_OPTIONS
make build
