#!/usr/bin/env bash
SYMLINK=/var/tmp/sage-jc4b6yulaujayb9sr94ia88eourzeqip0oidmas3
if [ ! -e $SYMLINK ]; then
    APP_PATH=`osascript \
-e 'set appAlias to ""' \
-e 'try' \
-e '  tell application "Finder" to set appAlias to application file id "org.computop.SageMath" as alias' \
-e 'end try' \
-e 'if AppAlias is not "" then' \
-e '  return POSIX path of appAlias' \
-e 'end if' \
`
    if [ "X${APP_PATH}X" == "XX" ]; then
	echo "Could not find the SageMath app!"
	exit 1
    else 
        ln -s $APP_PATH/Contents/Frameworks/Sage.framework/Versions/Current $SYMLINK
    fi
fi
$SYMLINK/local/bin/sage $@
