#! /bin/bash
SYMLINK=/var/tmp/sage-9.4-current
APP=SageMath-9-4.app
if [ ! -e $SYMLINK ]; then
    CURRENT=Contents/Frameworks/Sage.framework/Versions/Current
    LSREGISTER=/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister
    DUMP=$($LSREGISTER -apps ul -dump | grep $APP | grep -v Volumes | grep -v Trash)
    for ITEM in $DUMP; do
	if [ $(basename $ITEM) == $APP ]; then
	    ln -s $ITEM/$CURRENT $SYMLINK;
	    break;
	fi
    done
fi
if [ ! -e $SYMLINK ]; then
    echo Could not find $APP
    exit 1
fi
"$SYMLINK/local/bin/sage" "$@"
