name: macOS Sage base for Arm

on: [push]

jobs:
  build_package:
    name: Build Sage base for Arm

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          brew update
          brew install make cmake gfortran

      - name: Build base
        run: |
          cd Sage_base
          bash build_base.sh
          
      - name: Make tarball
        run: |
          mkdir artifacts
          cd Sage_base/sage
          tar cfz ../../artifacts/arm_base.tgz local

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arm_base
          path: ./artifacts
